config/routes.rb
Tiara::Application.routes.draw do  resources :records
  resources :records
  resources :courts

  put 'reindex' => 'sphinx#index', as: 'reindex'

  scope '/export' do
    root :to => 'export#index', as: 'exports'
    match ':resource' => 'export#export', as: 'export'
  end

  root :to => 'pages#home'
end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :court

  has_one :residence, :class_name => 'Address'
  accepts_nested_attributes_for :residence

  has_many :names
  accepts_nested_attributes_for :names, :allow_destroy => :true,
      :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }

  has_many :transfers
  accepts_nested_attributes_for :transfers, :allow_destroy => :true,
      :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }

  has_many :beneficiaries
  accepts_nested_attributes_for :beneficiaries, :allow_destroy => :true,
      :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }

  delegate :name, to: :court, prefix: true, allow_nil: true
  delegate :city, to: :residence, prefix: true, allow_nil: true

  delegate :last, to: 'names.last', prefix: :name, allow_nil: true
  delegate :first, to: 'names.last', prefix: :name, allow_nil: true
  delegate :middle, to: 'names.last', prefix: :name, allow_nil: true
  delegate :title, to: 'names.last', prefix: :name, allow_nil: true

  def initiated_on
    [initiated_on_year, initiated_on_month, initiated_on_date].delete_if(&:blank?).join('/')
  end
  def died_on
    [died_on_year, died_on_month, died_on_date].delete_if(&:blank?).join('/')
  end
  def suspended_on
    [suspended_on_year, suspended_on_month, suspended_on_date].delete_if(&:blank?).join('/')
  end
  def paid_on
    [paid_on_year, paid_on_month, paid_on_date].delete_if(&:blank?).join('/')
  end
  def reinstated_on
    [reinstated_on_year, reinstated_on_month, reinstated_on_date].delete_if(&:blank?).join('/')
  end
  def withdrawn_on
    [withdrawn_on_year, withdrawn_on_month, withdrawn_on_date].delete_if(&:blank?).join('/')
  end

  # THINKING SPHINX

  # These are the indexes you may search on. The first element of an array is 
  # the label in the drop down. The second is the name of the sphinx index.
  SEARCH_INDEXES = [
    ['Keywords', 'keyword'], 
    ['First Name', 'name_first'],
    ['Middle Name', 'name_middle'],
    ['Last Name', 'name_last']
  ]

  define_index do
    indexes names.first,    as: :name_first,     sortable: true
    indexes names.middle,   as: :name_middle,    sortable: true
    indexes names.last,     as: :name_last,      sortable: true
    indexes names.title,    as: :name_title,     sortable: true
    indexes court.name,     as: :court_name,     sortable: true, facet: true
    indexes residence.city, as: :residence_city, sortable: true, facet: true
    indexes died_on_year,   as: :died_on_year,   sortable: true, facet: true

    has claim_id,           as: :claim_id, sortable: true
    has court_id
    has names.id
    set_property :delta => true
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def index
    options = {}.tap do |option|
      option[:page]      = params[:page]
      option[:star]      = true
      option[:per_page]  = 100

      if params[:order]
        option[:order]     = params[:order]
        option[:sort_mode] = params[:sort_mode].blank? ? :asc : params[:sort_mode].to_sym
      else
        # Default sort is by weight, descending
        option[:order]     = '@weight DESC'
      end

      option[:conditions] = {}.tap do |condition|
        # Facets
        condition[:court_name]      = sanitize(params[:court_name]) if params[:court_name]
        condition[:residence_city]  = sanitize(params[:residence_city]) if params[:residence_city]
        condition[:died_on_year]    = sanitize(params[:died_on_year]) if params[:died_on_year]

        # Search query depending on index
        condition[:name_first]  = params[:search] if params[:index] == 'name_first'
        condition[:name_middle] = params[:search] if params[:index] == 'name_middle'
        condition[:name_last]   = params[:search] if params[:index] == 'name_last'
      end
    end

    @records = Record.search (params[:index] == 'keyword') ? params[:search] : '', options
    @facets = @records.facets
  end

  def show
    @record = Record.find(params[:id])
  end

  def new
    @record = Record.new
    @record.residence = @record.build_residence
    @record.names.build
  end

  def edit
    @record = Record.find(params[:id])
  end

  def create
    @record = Record.new(params[:record])

    if @record.save
      flash[:notice] = 'Record was successfully created.'
      redirect_to record_path(@record)
    else
      flash.now[:error] = 'There was a problem creating the record.'
      render :new
    end
  end

  def update
    @record = Record.find(params[:id])
    @record.attributes = params[:record]

    if @record.updated_at.to_s != params[:updated_at]
      flash[:error] = "Another user has updated this record since you've opened it. The record was not saved. Pleased try again."
      redirect_to record_path(@record)
    elsif @record.save
      flash[:notice] = 'Record was successfully updated.'
      redirect_to record_path(@record)
    else
      flash.now[:error] = 'There was a problem updating the record.'
      render :edit
    end
  end

  def destroy
    @record = Record.find(params[:id])

    if @record.destroy
      flash[:notice] = 'The record was successfully deleted.'
      redirect_to records_url
    else
      flash[:error] = 'There was a problem deleting the record.'
      redirect_to records_url
    end
  end

  protected
  def sanitize(str)
    str.gsub('/', '\/') 
  end
end

app/helpers/records_helper.rb
module RecordsHelper

  # `link_to_sortable` is a thin wrapper for turning column headers into links
  # that allow users to sort
  #
  # `text` - link text
  # `index` - thinking sphinx index
  # `parameters` - params hash from a request
  def link_to_sortable(text, index, parameters)
    p = parameters.clone
    p[:order]     = index
    p[:sort_mode] = p[:sort_mode].blank? || p[:sort_mode] == 'desc' ? 'asc' : 'desc'
    link_to text, records_path(p)
  end
end

app/views/records/_beneficiary_fields.html.erb
<div class="field-beneficiary">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :relationship %>
    <%= f.text_field :relationship %>
  </div>

  <div class="action">
    <br>
    <%= f.link_to_remove "Remove" %>
  </div>
</div>

app/views/records/_form.html.erb
<%= nested_form_for(@record) do |f| %>
  <%= hidden_field_tag :updated_at, @record.updated_at %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit disable_with: 'Please wait...' %>
  </div>

  <%= field_set_tag 'Names' do %>
    <%= f.fields_for :names %>
    <%= f.link_to_add "Add a Name", :names %>
  <% end %>

  <%= f.fields_for :residence %>

  <%= field_set_tag 'Courts' do %>
    <div class="field">
      <%= f.label :court %>
      <%= f.collection_select(:court_id, Court.all, :id, :to_s, {:include_blank => true}) %>
    </div>

    <%= f.fields_for :transfers %>
    <%= f.link_to_add "Add a Transfer", :transfers %>
  <% end %>

  <%= field_set_tag 'Initiation' do %>
    <div class="field">
      <%= f.label :register_no, 'Register Number' %>
      <%= f.number_field :register_no %>
    </div>

    <div class="field">
      <%= f.label :age_at_initiation %><br />
      <%= f.number_field :age_at_initiation %>
    </div>

    <%= date_to_text_selectors('initiated_on', f, @record) %>
  <% end %>

  <%= field_set_tag 'Beneficiaries' do %>
    <%= f.fields_for :beneficiaries %>
    <%= f.link_to_add "Add a Beneficiary", :beneficiaries %>
  <% end %>

  <%= field_set_tag 'Suspended On' do %>
    <%= date_to_text_selectors('suspended_on', f, @record) %>
  <% end %>
  <%= field_set_tag 'Reinstated On' do %>
    <%= date_to_text_selectors('reinstated_on', f, @record) %>
  <% end %>
  <%= field_set_tag 'Withdrawn On' do %>
    <%= date_to_text_selectors('withdrawn_on', f, @record) %>
  <% end %>
  <%= field_set_tag 'Died On' do %>
    <%= date_to_text_selectors('died_on', f, @record) %>
  <% end %>

  <%= field_set_tag 'Paid On' do %>
    <%= date_to_text_selectors('paid_on', f, @record) %>
  <% end %>

  <%= field_set_tag 'Death Claim Number' do %>
    <div class="field">
      <%= f.number_field :claim_id %>
    </div>
  <% end %>

  <%= field_set_tag 'Notes' do %>
    <div class="field">
      <%= f.label :notes, 'Public Notes' %><br />
      <%= f.text_area :notes %>
    </div>

    <div class="field">
      <%= f.label :notes_private, 'Private Notes' %><br />
      <%= f.text_area :notes_private %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit disable_with: 'Please wait...' %>
  </div>
<% end %>

app/views/records/_links.html.erb
<p>
  <%= link_to 'Edit', edit_record_path(@record) %> |
  <%= link_to 'Delete', record_path(@record), method: :delete, confirm: 'Are you sure you wish to delete this record? This operation cannot be undone.' %> |
  <%= link_to 'Back', records_path %>
</p>

app/views/records/_name_fields.html.erb
<%# `f` is a form builder %>
<div class="field-name">
  <div class="field field-name-last">
    <%= f.label :last %>
    <%= f.text_field :last %>
  </div>

  <div class="field field-name-first">
    <%= f.label :first %>
    <%= f.text_field :first %>
  </div>

  <div class="field field-name-middle">
    <%= f.label :middle %>
    <%= f.text_field :middle %>
  </div>

  <div class="field field-name-title">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="action">
    <br>
    <%= f.link_to_remove "Remove" %>
  </div>
</div>

app/views/records/_residence_fields.html.erb
<%= field_set_tag 'Residence' do %>
  <div class="field-residence">
    <div class="field">
      <%= f.label :line1, 'Street' %>
      <%= f.text_field :line1 %>
    </div>
    <div class="field">
      <%= f.label :city, 'City' %>
      <%= f.text_field :city %>
    </div>
    <div class="field">
      <%= f.label :state, 'State' %>
      <%= f.text_field :state %>
    </div>
  </div>
<% end %>

app/views/records/_transfer_fields.html.erb
<div class="field-transfer">
  <div class="field">
    <%= f.label :transferred, 'Transferred to' %><br />
    <%= f.collection_select(:court_id, Court.all, :id, :to_s, {:include_blank => true}) %>
  </div>

  <div class="field">
    <%= f.label :transferred_on_month, 'Month' %><br />
    <%= f.select(:transferred_on_month, options_for_select(ApplicationHelper::MONTH_OPTIONS_FOR_SELECT, f.object.transferred_on_month), {include_blank: true}) %>
  </div>

  <div class="field">
    <%= f.label :transferred_on_date, 'Day' %><br />
    <%= f.text_field :transferred_on_date, class: 'field-date-day' %>
  </div>

  <div class="field">
    <%= f.label :transferred_on_year, 'Year' %><br />
    <%= f.text_field :transferred_on_year, class: 'field-date-year' %>
  </div>

  <div class="action">
    <br>
    <%= f.link_to_remove "Remove" %>
  </div>
</div>

app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render 'form' %>

<%= link_to 'Cancel', records_path %>

app/views/records/index.html.erb
<h1>Records</h1>

<div id="top">
  <%= form_tag records_path, :method => 'get' do %>
    <%= label_tag :search %>
    <%= text_field_tag :search, params[:search] %>
    <%= select_tag "index", options_for_select(Record::SEARCH_INDEXES, selected: params[:index]) %>
    <%= submit_tag "Search", :name => nil %>
  <% end %>
</div>

<div id="sidebar">
  <% @facets.each do |facet, facet_options| %>
    <div class="facet-name"><%= facet.to_s.humanize %></div>
    <ul class="facet-list">
    <% facet_options.sort_by{|a| a[0].to_s}.each do |option, count| %>
      <% next if option.blank? %>
      <li><%= link_to "#{option} (#{count})",
        params.merge({facet => option, :page => 1}) %></li>
    <% end %>
    </ul>
  <% end %>
</div>

<div id="main">
  <p><%= link_to 'New Record', new_record_path %></p>

  <table>
    <thead>
      <tr>
        <th><%= link_to_sortable 'Claim',  'claim_id', params %></th>
        <th><%= link_to_sortable 'Last',   'name_last',   params %></th>
        <th><%= link_to_sortable 'First',  'name_first',  params %></th>
        <th><%= link_to_sortable 'Middle', 'name_middle', params %></th>
        <th><%= link_to_sortable 'Title',  'name_title',  params %></th>
        <th><%= link_to_sortable 'Court',  'court_name',  params %></th>
        <th><%= link_to_sortable 'Residence', 'residence_city',  params %></th>
        <th><%= link_to_sortable 'Year of Death', 'died_on_year',  params %></th>
      </tr>
    </thead>

    <tbody>
      <% @records.each do |record| %>
        <tr>
          <td><%= link_to record.claim_id, record %></td>
          <td><%= record.name_last %></td>
          <td><%= record.name_first %></td>
          <td><%= record.name_middle %></td>
          <td><%= record.name_title %></td>
          <td><%= record.court_name %></td>
          <td><%= record.residence_city %></td>
          <td><%= record.died_on_year %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @records %>

  <p><%= link_to 'New Record', new_record_path %></p>
</div>

app/views/records/new.html.erb
<h1>New record</h1>

<%= render 'form' %>

<%= link_to 'Cancel', records_path %>

app/views/records/show.html.erb
<%= render 'links' %>

<div id="names">
  <% @record.names.each do |name| %>
    <p>
      <b>Name last:</b>
      <%= name.last %>
    </p>

    <p>
      <b>Name first:</b>
      <%= name.first %>
    </p>

    <p>
      <b>Name middle:</b>
      <%= name.middle %>
    </p>

    <p>
      <b>Title:</b>
      <%= name.title %>
    </p>
    <hr>
  <% end %>
</div>

<p>
  <div><b>Residence:</b></div>
  <div><%= @record.residence.line1 %></div>
  <div><%= @record.residence.city %></div>
  <div><%= @record.residence.state %></div>
  <div><%= @record.residence.zip %></div>
</p>
<hr>

<p>
  <b>Court:</b>
  <%= @record.court %>

  <% @record.transfers.each do |transfer| %>
    <div><%= transfer.court.name %></div>
    <div><%= transfer.transferred_on_year %></div>
    <div><%= transfer.transferred_on_month %></div>
    <div><%= transfer.transferred_on_date %></div>
  <% end %>
</p>
<hr>

<p>
  <b>Register Number:</b>
  <%= @record.register_no %>
</p>
<p>
  <b>Age at initiation:</b>
  <%= @record.age_at_initiation %>
</p>
<p>
  <b>Initiated at:</b>
  <%= @record.initiated_on %>
</p>
<hr>

<% @record.beneficiaries.each do |beneficiary| %>
  <p>
    <b>Beneficiary:</b>
    <div><%= beneficiary.name %></div>
    <div><%= beneficiary.relationship %></div>
  </p>
<% end %>
<hr>


<p>
  <b>Suspended at:</b>
  <%= @record.suspended_on %>
</p>

<p>
  <b>Reinstated at:</b>
  <%= @record.reinstated_on %>
</p>

<p>
  <b>Withdrawn at:</b>
  <%= @record.withdrawn_on %>
</p>
<p>
  <b>Died at:</b>
  <%= @record.died_on %>
</p>

<p>
  <b>Paid at:</b>
  <%= @record.paid_on %>
</p>
<hr>

<p>
  <b>Death Claim Number:</b>
  <%= @record.claim_id %>
</p>

<hr>


<p>
  <b>Notes:</b>
  <%= @record.notes %>
</p>

<p>
  <b>Private Notes:</b>
  <%= @record.notes_private %>
</p>

<%= render 'links' %>