config/routes.rb
Tiara::Application.routes.draw do  resources :records
  resources :records
  resources :courts

  put 'reindex' => 'sphinx#index', as: 'reindex'

  scope '/export' do
    root :to => 'export#index', as: 'exports'
    match ':resource' => 'export#export', as: 'export'
  end

  root :to => 'pages#home'
end

app/models/court.rb
class Court < ActiveRecord::Base
  has_and_belongs_to_many :ethnicities
  has_many :records 

  validates :gender, inclusion: {in: %(Men Women Mixed)}, allow_nil: true

  before_destroy :ensure_no_records 

  delegate :year, :month, :day, to: :instituted_on, prefix: true, allow_nil: true
  delegate :year, :month, :day, to: :closed_on,     prefix: true, allow_nil: true

  def to_s
    "#{code} - #{name}"
  end

  define_index do
    indexes name, sortable: true
    indexes street
    indexes town, sortable: true, facet: true
    indexes gender, sortable: true
    indexes notes
    indexes closed_on
    indexes instituted_on
  end

  private
  def ensure_no_records
    return false unless records.empty?
  end
end

app/controllers/courts_controller.rb
class CourtsController < ApplicationController
  # GET /courts
  # GET /courts.json
  def index
    if params[:search] or params[:town] or params[:gender] or params[:closed_on]
      field_facets = {town:      params[:town], 
                      gender:    params[:gender],
                      closed_on: params[:closed_on]
                     }.reject {|k,v| v.nil?}
      @courts = Court.search params[:search], 
        page: params[:page], 
        conditions: field_facets,
        star: true, 
        per_page: 100
      @facets = @courts.facets
    else
      @courts = Court.includes(:ethnicities).page(params[:page]).per(100)
      @facets = Court.facets
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courts }
    end
  end

  # GET /courts/1
  # GET /courts/1.json
  def show
    @court = Court.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @court }
    end
  end

  # GET /courts/new
  # GET /courts/new.json
  def new
    @court = Court.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @court }
    end
  end

  # GET /courts/1/edit
  def edit
    @court = Court.find(params[:id])
  end

  # POST /courts
  # POST /courts.json
  def create
    @court = Court.new(params[:court])

    respond_to do |format|
      if @court.save
        format.html { redirect_to @court, notice: 'Court was successfully created.' }
        format.json { render json: @court, status: :created, location: @court }
      else
        format.html { render action: "new" }
        format.json { render json: @court.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courts/1
  # PUT /courts/1.json
  def update
    @court = Court.find(params[:id])

    respond_to do |format|
      if @court.update_attributes(params[:court])
        format.html { redirect_to @court, notice: 'Court was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @court.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courts/1
  # DELETE /courts/1.json
  def destroy
    @court = Court.find(params[:id])
    @court.destroy

    respond_to do |format|
      format.html { redirect_to courts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/views/courts/_form.html.erb
<%= form_for(@court) do |f| %>
  <% if @court.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@court.errors.count, "error") %> prohibited this court from being saved:</h2>

      <ul>
      <% @court.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit disable_with: 'Please wait...' %>
  </div>

  <%= field_set_tag 'Information' do %> 
    <div class="field">
      <%= f.label :code, 'Court Number' %><br />
      <%= f.text_field :code %>
    </div>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :street %><br />
      <%= f.text_field :street %>
    </div>
    <div class="field">
      <%= f.label :town %><br />
      <%= f.text_field :town %>
    </div>
  <% end %>

  <%= field_set_tag 'Dates' do %>
    <div class="field">
      <%= f.label :instituted_on %><br />
      <%= text_field_tag 'court[instituted_on(1i)]', @court.instituted_on_year, maxlength: 4, size: 4 %>
      <%= select_month @court.instituted_on, prefix: 'court', field_name: 'instituted_on(2i)', include_blank: true %>
      <%= select_day   @court.instituted_on, prefix: 'court', field_name: 'instituted_on(3i)', include_blank: true %>
    </div>

    <div class="field">
      <%= f.label :closed_on %><br />
      <%= text_field_tag 'court[closed_on(1i)]', @court.closed_on_year, maxlength: 4, size: 4 %>
      <%= select_month @court.closed_on, prefix: 'court', field_name: 'closed_on(2i)', include_blank: true %>
      <%= select_day   @court.closed_on, prefix: 'court', field_name: 'closed_on(3i)', include_blank: true %>
    </div>
  <% end %>
 
  <%= field_set_tag 'Demographics' do %>
    <div class="field">
      <%= f.label :gender %><br />
      <%= f.text_field :gender %>
    </div>

   <div class="field">
      <%= f.label :ethnicities %><br />
      <%= f.collection_select :ethnicity_ids, Ethnicity.all, :id, :name, {selected: @court.ethnicity_ids}, {multiple: true} %>
    </div>
  <% end %>

  <%= field_set_tag 'Notes' do %>
    <div class="field">
      <%= f.text_area :notes %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit disable_with: 'Please wait...' %>
  </div>
<% end %>

app/views/courts/edit.html.erb
<h1>Editing court</h1>

<%= render 'form' %>

<%= link_to 'Cancel', court_path(@court) %>

app/views/courts/index.html.erb
<div id="courts"></div>

<h1>Courts</h1>

<div id="top">
  <%= form_tag courts_path, :method => 'get' do %>
      <%= label_tag :search %>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
  <% end %>
</div>

<div id="sidebar">
  <% @facets.each do |facet, facet_options| %>
    <div class="facet-name"><%= facet.to_s.humanize %></div>
    <ul class="facet-list">
    <% facet_options.sort_by{|a| a[0].to_s}.each do |option, count| %>
      <% next if option.nil? %>
      <li><%= link_to "#{option} (#{count})",
        params.merge({facet => option, :page => 1}) %></li>
    <% end %>
    </ul>
  <% end %>
</div>

<div id="main">
  <p><%= link_to 'New Court', new_court_path %></p>

  <table>
    <thead>
      <tr>
        <th>Number</th>
        <th>Name</th>
        <th>Town</th>
        <th>Street</th>
        <th>Instituted at</th>
      </tr>
    </thead>

    <tbody>
      <% @courts.each do |court| %>
        <tr>
          <td><%= link_to court.code, court %></td>
          <td><%= court.name %></td>
          <td><%= court.town %></td>
          <td><%= court.street %></td>
          <td><%= court.instituted_on %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @courts %>

  <br />

  <p><%= link_to 'New Court', new_court_path %></p>

</div>

app/views/courts/new.html.erb
<h1>New court</h1>

<%= render 'form' %>

<%= link_to 'Cancel', courts_path %>

app/views/courts/show.html.erb
<p>
  <%= link_to 'Edit', edit_court_path(@court) %> |
  <%= link_to 'Back', courts_path %>
</p>

<p>
  <b>Court Number:</b>
  <%= @court.code %>
</p>

<p>
  <b>Name:</b>
  <%= @court.name %>
</p>

<p>
  <b>Street:</b>
  <%= @court.street %>
</p>

<p>
  <b>Town:</b>
  <%= @court.town %>
</p>

<p>
  <b>Instituted at:</b>
  <%= @court.instituted_on %>
</p>

<p>
  <b>Gender:</b>
  <%= @court.gender %>
</p>

<p>
  <b>Closed:</b>
  <%= @court.closed_on %>
</p>

<p>
  <b>Notes:</b>
  <%= @court.notes %>
</p>

<p>
  <b>Ethnicities:</b>
  <%= @court.ethnicities.map{|e| e.name}.join(', ') %>
</p>

<p>
  <%= link_to 'Edit', edit_court_path(@court) %> |
  <%= link_to 'Back', courts_path %>
</p>