config/routes.rb
Tiara::Application.routes.draw do  resources :records
  resources :records
  resources :courts

  put 'reindex' => 'sphinx#index', as: 'reindex'

  scope '/export' do
    root :to => 'export#index', as: 'exports'
    match ':resource' => 'export#export', as: 'export'
  end

  root :to => 'pages#home'
end

app/controllers/export_controller.rb
require 'csv'

class ExportController < ApplicationController
  RESOURCES = %w(address beneficiary court name record transfer)

  def index
  end

  def export
    if RESOURCES.include? params[:resource]
      @resource = params[:resource].camelize.constantize
      to_csv(@resource.all, "#{params[:resource]}.csv")
    else
      flash.now[:error] = 'There was a problem exporting your data'
      render :index
    end
  end

  private
  def to_csv(records, filename)
    csv_string = CSV.generate do |csv|
      # header
      csv << records.map(&:attributes).map(&:keys).first

      records.each do |record|
        csv << record.attributes.values
      end
    end

    send_data(csv_string, type: 'text/csv', filename: filename)
  end
end

app/views/export/index.html.erb
<div class="page-header">
  <h1>Export Data</h1>
</div>

<ul>
  <li><%= link_to 'Addresses', export_path(resource: 'address') %></li>
  <li><%= link_to 'Beneficiaries', export_path(resource: 'beneficiary') %></li>
  <li><%= link_to 'Courts', export_path(resource: 'court') %></li>
  <li><%= link_to 'Names', export_path(resource: 'name') %></li>
  <li><%= link_to 'Records', export_path(resource: 'record') %></li>
  <li><%= link_to 'Transfers', export_path(resource: 'transfer') %></li>
</ul>